Merge improved date parser into existing bot
szegedai/hun-appointment-chatbot pull request #39
Opened 2022-01-13 12:31 UTC by GellertPalfi

Since the logic has been completely rewritten, i don't see any conflicts that would cause problems

2022-01-17 10:57 UTC, mindedj requested changes
It seems there are conflicts, you need to match the directory structure of refactor_nodejs (actions -> action_server, backend -> rasa_server)

2022-01-26 18:38 UTC, mindedj reviewed
My suggestions are mostly for refactoring, I could not find anything that could be done 'easier'

2022-01-26 18:38 UTC, mindedj commented on rasa_server/.gitignore
> +backend/models/
rasa_server/models/

2022-01-26 18:38 UTC, mindedj commented on action_server/actions.py
> +        if not rule_blocks.if_text_has_datetime():
With reversed if statement this block can get rid of 1 level of indentation

2022-01-26 19:04 UTC, mindedj approved these changes

2022-01-26 19:27 UTC, nsomabalint commented
As discussed we will address all comments by @mindedj in a future PR as we should do a larger refactor anyways. I'll merge this for now.

2022-01-26 19:32 UTC, nsomabalint approved these changes

2022-01-26 20:02 UTC, merged